# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=random.randint, unique=True),
        ),
    ]
